service: hackathonUDD

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    ENVIRONMENT: ${self:provider.stage}
    USUARIOS_TABLE: ${self:custom.usuariosTable}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
          Resource:
            - !GetAtt UsuariosTable.Arn

custom:
  usuariosTable: Usuarios-${sls:stage}
  prune:
    automatic: true
    number: 1

functions:
  users:
    handler: src/handlers/users/usersHandler.handler
    events:
      - http:
          path: users
          method: post
          cors: true
      - http:
          path: users
          method: get
          cors: true
      - http:
          path: users/{idUsuario}
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin

resources:
  Resources:
    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usuariosTable}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: idUsuario
            AttributeType: S
        KeySchema:
          - AttributeName: idUsuario
            KeyType: HASH
